
DROP TABLE IF EXISTS dishes CASCADE;

CREATE TABLE dishes (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  price INTEGER NOT NULL,
  image_url VARCHAR(255) NOT NULL,
  isDeleted BOOLEAN DEFAULT FALSE
);
